"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { Provider } from "react-redux"; // Import Redux Provider
// import store from "../app/store/store"; // Import the Redux store
import { useEffect } from "react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <Provider store={store}> */}
         
          {children}
        {/* </Provider> */}
      </body>
    </html>
  );
}
